version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mensajesdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    networks:
      - datalogger_net

  srvwildfly:
    image: dockerwildfly
    container_name: srvwildfly
    hostname: srvwildfly
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mensajesdb
      - DB_USER=root
      - DB_PASSWORD=root
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - postgres
    networks:
      - datalogger_net

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ups123@ups.com.ec
      PGADMIN_DEFAULT_PASSWORD: ups123
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - datalogger_net

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8083:8080"
    environment:
      SWAGGER_JSON: /restful/openapi.yaml
    volumes:
      - ./openapi.yaml:/restful/openapi.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.16.0
    ports:
      - 6831:6831/udp
      - 16686:16686
    depends_on:
      - srvwildfly
    networks:
      - datalogger_net

  angular-frontend: 
    image: dockerfronted
    container_name: angular-frontend
    ports:
      - 4200:4200
    depends_on:
      - srvwildfly
    networks:
      - datalogger_net

networks:
  datalogger_net: