openapi: 3.0.0
info:
  title: Mensaje Usuario API
  description: API para gestionar mensajes de usuarios
  version: 1.0.0
servers:
  - url: http://localhost:8080/demo64/rs
    description: Servidor local
paths:
  /mensaje:
    post:
      summary: Crear un nuevo mensaje
      operationId: crearMensaje
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MensajesUsuarios'
      responses:
        '201':
          description: Mensaje creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    put:
      summary: Actualizar un mensaje existente
      operationId: actualizarMensaje
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MensajesUsuarios'
      responses:
        '200':
          description: Mensaje actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MensajesUsuarios'
        '404':
          description: Mensaje no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      summary: Borrar un mensaje
      operationId: borrarMensaje
      parameters:
        - name: id
          in: query
          description: ID del mensaje a borrar
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Mensaje borrado exitosamente
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Error al eliminar el mensaje
          content:
            application/json:
              schema:
                type: string
  /mensaje/list:
    get:
      summary: Listar todos los mensajes
      operationId: listarMensajes
      responses:
        '200':
          description: Lista de mensajes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MensajesUsuarios'
        '404':
          description: No se encontraron mensajes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    MensajesUsuarios:
      type: object
      properties:
        codigo:
          type: integer
          example: 3
        nombre:
          type: string
          example: jeison
        correo:
          type: string
          example: dasdadasd
        mensaje:
          type: string
          example: dsadadasdasd
    ErrorMessage:
      type: object
      properties:
        code:
          type: integer
          example: 1
        message:
          type: string
          example: ok
